### ISSUE TITLE
mu returned by instaseis and location error of receivers

### ISSUE THREAD

**Issue by lileipku00** [krischer/instaseis#69]
Hi, I got two questions on `instaseis` and appreciate any clarification .

1. `db.get_seismograms(src, rec, components='Z', ..., return_obspy_stream=False)` returns a dict with Z seismogram and another key `mu`. What is this `mu`? In the doc, it just says

> Return type:  A obspy.core.stream.Stream object or a dictionary with NumPy arrays as values

2. In the direct source-receiver simulations by `AxiSEM`, the real receiver locations can be different from those requested. For instance, `[30.4N, 0E]` is requested, but `[30.45, 0E]` is returned. What makes this shift? 
`AxiSEM` provides both coordinates in output files. But `Instaseis` returns only the requested station locations. So I have no idea about the spatial shift. Is there any way to know this info?

**Comment by sstaehler** [comment]
1. The second value is mu (shear modulus) at the source location

2. In AxiSEM, the receiver is moved to the next GLL point. In Instaseis, the receiver is always at the requested position, since we're doing an interpolation of the wavefield by evaluation of the Legendre polynomials (see the Instaseis paper, section 2.3 https://www.solid-earth.net/6/701/2015/)

**Comment by lileipku00** [comment]
Thanks for explanation, Simon.
